service: stacknest
runtime: nodejs20

handlers:
  - url: /sw\.js
    static_files: dist/sw.js
    upload: dist/sw\.js
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      X-Frame-Options: "SAMEORIGIN"

  - url: /assets
    static_dir: dist/assets
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      X-Frame-Options: "SAMEORIGIN"

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      X-Frame-Options: "SAMEORIGIN"
