name: Deploy Backend to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into GCE and pull latest backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_INSTANCE_NAME }}.${{ secrets.GCP_PROJECT_ID }}.internal << 'EOF'
            cd ~/Stacknest/Backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
