name: Deploy Frontend to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React App to GAE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: Frontend

      - name: Create .env.production file
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> Frontend/.env.production
          echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}" >> Frontend/.env.production
          echo "VITE_GOOGLE_CLIENG_ID=${{ secrets.VITE_GOOGLE_CLIENG_ID }}" >> Frontend/.env.production
          echo "VITE_VAPID_PUBLIC_KEY=${{ secrets.VITE_VAPID_PUBLIC_KEY }}" >> Frontend/.env.production
          echo "VITE_APP_MODE=${{ secrets.VITE_APP_MODE }}" >> Frontend/.env.production
          echo "VITE_TURN_CRED=${{ secrets.VITE_TURN_CRED }}" >> Frontend/.env.production
          echo "VITE_INSTANCE_IP=${{ secrets.VITE_INSTANCE_IP }}" >> Frontend/.env.production
          echo "VITE_DEBOUNCE_DELAY=${{ secrets.VITE_DEBOUNCE_DELAY }}" >> Frontend/.env.production
          echo "VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY }}" >> Frontend/.env.production
          echo "VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}" >> Frontend/.env.production
          echo "VITE_STRIPE_KEY=${{ secrets.VITE_STRIPE_KEY }}" >> Frontend/.env.production

      - name: Build React App
        run: npm run build
        working-directory: Frontend

      - name: List files in dist directory (For debugging)
        run: ls -R Frontend/dist

      - name: Setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Google App Engine
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          cd Frontend
          gcloud app deploy --quiet
