name: Deploy Frontend to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React App to GAE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: Frontend

      - name: Build React App
        run: npm run build
        working-directory: Frontend

      - name: List files in dist directory (For debugging)
        run: ls -R Frontend/dist

      - name: Setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google App Engine
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          cd Frontend
          # Ensure we're deploying the correct folder
          gcloud app deploy --quiet
